# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3f5ea266809b6da46dcd93e21209117a09a9db5b1814aa39e4c2b0860c9b8b728197144a8012932dec06d630c1b153c46af47bb5367966f34f3055ae7d70ad8

test:
  secret_key_base: 888268e21db7301cb6bf90afe739da11e24e1da4e1941a94937e1e1c29d9442d9c6b81cd41e2670e608784e1f903f33472b699d9d40da81602e47313599b071b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
